name: Build Resumes

on:
  push:
    paths:
      - "resume.md"
      - "resumes/private/resume_private.md"

jobs:
  build-resumes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Pandoc and LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-latex-base texlive-xetex texlive-fonts-recommended

      # Federal Resume
      - name: Build Federal Resume (DOCX)
        run: |
          pandoc resume.md -o resumes/federal/resume.docx

      - name: Build Federal Resume (PDF)
        run: |
          pandoc resume.md -o resumes/federal/resume.pdf

      # Private Resume
      - name: Build Private Resume (DOCX)
        run: |
          pandoc resumes/private/resume_private.md -o resumes/private/resume.docx

      - name: Build Private Resume (PDF)
        run: |
          pandoc resumes/private/resume_private.md -o resumes/private/resume.pdf

      - name: Upload all resumes
        uses: actions/upload-artifact@v3
        with:
          name: resumes
          path: resumes/

      # Build all resume variants
      - name: Build Variant Resumes
        run: |
          for file in resumes/variants/*.md; do
            name=$(basename "$file" .md)
            pandoc "$file" -o "resumes/variants/${name}.docx"
            pandoc "$file" -o "resumes/variants/${name}.pdf"
          done
