name: Build Resume

on:
  push:
    paths:
      - "resume.md"

jobs:
  build-resume:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Pandoc and LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-latex-base texlive-xetex texlive-fonts-recommended

      - name: Convert to DOCX
        run: |
          pandoc resume.md -o resumes/federal/resume.docx

      - name: Convert to PDF
        run: |
          pandoc resume.md -o resumes/federal/resume.pdf

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: resumes
          path: resumes/federal/
